global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'sms_dashboard'
    static_configs:
      - targets: ['localhost:8000']

rule_files:
  - 'alert_rules.yml'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'localhost:9093'